
###################### canais Brasil ######################
<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]CNN Brasil (SP)[/COLOR][/B]</title>
<link>https://video01.soultv.com.br/cnnbrasil/cnnbrasil/chunklist_w380738139.m3u8</link>
<thumbnail>https://archive.org/download/CNN-brasil_202305/CNN%20brasil.jpg</thumbnail>
<fanart>https://archive.org/download/CNN-brasil_202305/CNN%20brasil.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]catve (PR)[/COLOR][/B]</title>
<link>https://5b33b873179a2.streamlock.net:1443/live/livestream/chunklist_w143651179.m3u8</link>
<thumbnail>https://archive.org/download/CATVE/CATVE.jpg</thumbnail>
<fanart>https://archive.org/download/CATVE/CATVE.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Brasil[/COLOR][/B]</title>
<link>https://5cf4a2c2512a2.streamlock.net/rbtv/rbtv/chunklist_w618668246.m3u8</link>
<thumbnail>https://archive.org/download/rede-brasil/Rede%20Brasil.jpg</thumbnail>
<fanart>https://archive.org/download/rede-brasil/Rede%20Brasil.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Arapuan (PB)[/COLOR][/B]</title>
<link>https://5b7f3c45ab7c2.streamlock.net/arapuan/ngrp:arapuan_all/playlist.m3u8</link>
<thumbnail>https://ia601602.us.archive.org/29/items/TV-Arapuan-PB/TV%20Arapuan%20%28PB%29.jpg</thumbnail>
<fanart>https://archive.org/download/TV-Arapuan-PB/TV%20Arapuan%20%28PB%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Retro Cartoon (SP)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/retrotv/retrotv/chunklist_w178021133.m3u8</link>
<thumbnail>https://archive.org/download/retro-cartoon-channel/retro-cartoon-channel.jpg</thumbnail>
<fanart>https://archive.org/download/retro-cartoon-channel/retro-cartoon-channel.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Brasil (DF)[/COLOR][/B]</title>
<link>https://tvbrasil-stream.ebc.com.br/mux_video_ts/index-1.m3u8</link>
<thumbnail>https://archive.org/download/tv-brasil/TV%20Brasil.jpg</thumbnail>
<fanart>https://archive.org/download/tv-brasil/TV%20Brasil.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Nova Play (RJ)[/COLOR][/B]</title>
<link>https://srv4.zcast.com.br/tvnovaplay/tvnovaplay/chunklist_w211543607.m3u8</link>
<thumbnail>https://archive.org/download/tv-nova-play-rj/TV%20Nova%20Play%20%28RJ%29.jpg</thumbnail>
<fanart>https://archive.org/download/tv-nova-play-rj/TV%20Nova%20Play%20%28RJ%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Web Tv Cine (SP)[/COLOR][/B]</title>
<link>https://live01.livemustv.com.br/livemustv7426/livemustv7426/chunklist_w889668456.m3u8</link>
<thumbnail>https://archive.org/download/web-tv-cine-sp/Web%20Tv%20Cine%20%28SP%29.jpg</thumbnail>
<fanart>https://archive.org/download/web-tv-cine-sp/Web%20Tv%20Cine%20%28SP%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Xtreme (RS)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/xtremetv/xtremetv/chunklist_w855935957.m3u8</link>
<thumbnail>https://archive.org/download/TV-Xtreme-RS/Tv%20Xtreme%20%28RS%29.jpg</thumbnail>
<fanart>https://archive.org/download/TV-Xtreme-RS/Tv%20Xtreme%20%28RS%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Anime Tv[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/animetv/animetv/chunklist_w614716911.m3u8</link>
<thumbnail>https://archive.org/download/anime-tv-sp/Anime%20Tv%20%28SP%29.jpg</thumbnail>
<fanart>https://archive.org/download/anime-tv-sp/Anime%20Tv%20%28SP%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Loading (SP)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/loadingtv/loadingtv/chunklist_w2000795367.m3u8</link>
<thumbnail>https://archive.org/download/tv-carregando-sp/Tv%20Loading%20%28SP%29.jpg</thumbnail>
<fanart>https://archive.org/download/tv-carregando-sp/Tv%20Loading%20%28SP%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV MAX (RJ)[/COLOR][/B]</title>
<link>https://59f1cbe63db89.streamlock.net:1443/tvmax/_definst_/tvmax/chunklist_w681654246.m3u8</link>
<thumbnail>https://archive.org/download/TV-Max-RJ/TV%20MAX%20%28RJ%29.jpg</thumbnail>
<fanart>https://archive.org/download/TV-Max-RJ/TV%20MAX%20%28RJ%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canal 29 (SP)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/canal29/canal29/chunklist_w2125553746.m3u8</link>
<thumbnail>https://archive.org/download/canal-29-sp/Canal%2029%20%28SP%29.jpg</thumbnail>
<fanart>https://archive.org/download/canal-29-sp/Canal%2029%20%28SP%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Clouding TV (PA)[/COLOR][/B]</title>
<link>https://stmv1.paineltv.net/redeclonetv/redeclonetv/chunklist_w1963435910.m3u8</link>
<thumbnail>https://archive.org/download/rede-clouding-tv-pa/Rede%20Clouding%20TV%20%28PA%29.jpg</thumbnail>
<fanart>https://archive.org/download/rede-clouding-tv-pa/Rede%20Clouding%20TV%20%28PA%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Clássicos do Cinema (AM)[/COLOR][/B]</title>
<link>https://live01.livemustv.com.br/livemustv7426/livemustv7426/chunklist_w889668456.m3u8</link>
<thumbnail>https://archive.org/download/tv-classicos-do-cinema-am/Tv%20Cl%C3%A1ssicos%20do%20Cinema%20%28AM%29.jpg</thumbnail>
<fanart>https://archive.org/download/tv-classicos-do-cinema-am/Tv%20Cl%C3%A1ssicos%20do%20Cinema%20%28AM%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Jovem Pan (SP)[/COLOR][/B]</title>
<link>https://d6yfbj4xxtrod.cloudfront.net/out/v1/7836eb391ec24452b149f3dc6df15bbd/index_10.m3u8</link>
<thumbnail>https://archive.org/download/tv-jovem-pan-sp/TV%20Jovem%20Pan%20%28SP%29.jpg</thumbnail>
<fanart>https://archive.org/download/tv-jovem-pan-sp/TV%20Jovem%20Pan%20%28SP%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Vida (SP)[/COLOR][/B]</title>
<link>https://cvd1.cds.ebtcvd.net/live-redevida/smil:redevida.smil/live-redevida/480p/chunks.m3u8</link>
<thumbnail>https://archive.org/download/rede-vida-sp/Rede%20Vida%20%28SP%29.jpg</thumbnail>
<fanart>https://archive.org/download/rede-vida-sp/Rede%20Vida%20%28SP%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]CinePIX TV (RS)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/channel1/channel1/chunklist_w1984986092.m3u8</link>
<thumbnail>https://archive.org/download/cine-pix-tv-rs/CinePIX%20TV%20%28RS%29.jpg</thumbnail>
<fanart>https://archive.org/download/cine-pix-tv-rs/CinePIX%20TV%20%28RS%29.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Jetsons Tv[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/jetsontv/jetsontv/chunklist_w335361948.m3u8</link>
<thumbnail>https://archive.org/download/Jetsons-TV/Jetsons%20Tv.jpg</thumbnail>
<fanart>https://archive.org/download/Jetsons-TV/Jetsons%20Tv.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>
#############################
<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Gazeta (Rede Gazeta) (SP)[/COLOR][/B]</title>
<link>https://video02.logicahost.com.br/tvc21/tvc21/chunklist_w550742510.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/e203baa61a997851f879286d0e262b59.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/e203baa61a997851f879286d0e262b59.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Aracati (CE)[/COLOR][/B]</title>
<link>https://video04.logicahost.com.br/tvaracati/tvaracati/chunklist_w580829248.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/69cf38e0cd65c06291dc072f3f9270b1.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/69cf38e0cd65c06291dc072f3f9270b1.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Aratu (BA)[/COLOR][/B]</title>
<link>https://cdn.jmvstream.com/w/LVW-8379/LVW8379_rIq6ZYiIiA/chunklist_w432406488.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/69cf38e0cd65c06291dc072f3f9270b1.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/69cf38e0cd65c06291dc072f3f9270b1.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Osório News (RS)[/COLOR][/B]</title>
<link>https://serv2.videovox.pw/video13154/video13154/chunklist_w1567600312.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/40d7d18ac1b8c2e6b87ecf0e3410cad7.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/40d7d18ac1b8c2e6b87ecf0e3410cad7.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Ação[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230508chckpl1pnj1vb8udgn4g/1280x720_3071200_0_f.m3u8?i=475_2552</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/c8d4d9609cc02e156c6a9c81b9a7b0c4.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/c8d4d9609cc02e156c6a9c81b9a7b0c4.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime TV e Filmes[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230508chckv5h0dv5ctfsqc3a0/1280x720_3071200_0_f.m3u8?i=475_2153</link>
<thumbnail>https://img2.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_br_1920x1080_0.jpg</thumbnail>
<fanart>https://img2.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_br_1920x1080_0.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Comédia[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230508chcl0gp0dv5ctfsqcj90/1280x720_3071200_0_f.m3u8?i=475_2553</link>
<thumbnail>https://img3.static-ottera.com/prod/run/linear_channel/logo/366x206/br_comedy_bg.jpg</thumbnail>
<fanart>https://img3.static-ottera.com/prod/run/linear_channel/logo/366x206/br_comedy_bg.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Crime[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230508chcl1lrjdm8fonsft180/1280x720_3071200_0_f.m3u8?i=475_4864</link>
<thumbnail>https://img2.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_crime_16x9_1.jpg</thumbnail>
<fanart>https://img2.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_crime_16x9_1.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Espanto[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230508chcl2i9opv5pil6q61cg/1280x720_3071200_0_f.m3u8?i=475_4865</link>
<thumbnail>https://img3.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_cinespanto_16x9_1.jpg</thumbnail>
<fanart>https://img3.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_cinespanto_16x9_1.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Romance[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230508chcl3gpopv5pil6q6erg/1280x720_3071200_0_f.m3u8?i=475_4866</link>
<thumbnail>https://img3.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_romance_16x9_2.jpg</thumbnail>
<fanart>https://img3.static-ottera.com/prod/run/linear_channel/logo/366x206/runtime_romance_16x9_2.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]SBT Brasília (DF)[/COLOR][/B]</title>
<link>https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/chunklist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/fd15c014fe05063f466190fe351d91c5.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/fd15c014fe05063f466190fe351d91c5.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]AniTV (SP)[/COLOR][/B]</title>
<link>https://stmv.srvvox.com.br/otakusigntv/otakusigntv/chunklist_w1911371551.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3eabf05ad0127a53af71227f1fe132a1.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3eabf05ad0127a53af71227f1fe132a1.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]RBATV (Band PA) (PA)[/COLOR][/B]</title>
<link>https://5cf4a2c2512a2.streamlock.net/rbatv/rbatv/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/df0c35517ab2f2e9e6e63c1808730694.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/df0c35517ab2f2e9e6e63c1808730694.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Vila Real (Record (MT)[/COLOR][/B]</title>
<link>https://5a2b083e9f360.streamlock.net/tvmt/tvmt.sdp/chunklist_w1082639984.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/08bb2dcf3ec4ceeb988d9a6b19270047.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/08bb2dcf3ec4ceeb988d9a6b19270047.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]IMPD TV (SP)[/COLOR][/B]</title>
<link>https://58a4464faef53.streamlock.net/impd/ngrp:impd_all/chunklist_w1242162897_b1196000.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/dca3e8515eaaa4f897e40ec0ee001cb7.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/dca3e8515eaaa4f897e40ec0ee001cb7.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Vida (SP)[/COLOR][/B]</title>
<link>https://cvd1.cds.ebtcvd.net/live-redevida/smil:redevida.smil/live-redevida/480p/chunks.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/85e5f6b6aa459a384730e3b520e1e728.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/85e5f6b6aa459a384730e3b520e1e728.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Universal (SP)[/COLOR][/B]</title>
<link>https://644398c.ha.azioncdn.net/primary/tvuniversal_480p.sdp/chunklist_4ae5cd41-2b58-485d-bb7d-15dc9acb5b0b.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/1d8fb419ad2b89ff1302e149a9774bc5.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/1d8fb419ad2b89ff1302e149a9774bc5.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]GLN TV[/COLOR][/B]</title>
<link>https://stmv1.paineltv.net/glnfilmes/glnfilmes/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/44db0c12711ce2d991d60021cda8a8d2.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/44db0c12711ce2d991d60021cda8a8d2.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Vintage Tv (SP)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/webvintage/webvintage/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/1e7e289ab5c66e67ad623c5a1bec9f75.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/1e7e289ab5c66e67ad623c5a1bec9f75.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Classique TV [/COLOR][/B]</title>
<link>https://stmv1.srvif.com/classiquew/classiquew/chunklist_w675808009.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/f032a160e2b4cbb9de8f0080b845c9ca.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/f032a160e2b4cbb9de8f0080b845c9ca.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]AWTV (SP)[/COLOR][/B]</title>
<link>https://ebocast.ebosystems.com.br:3070/live/awtvlive.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/862465d1835288b2ae6d11f27507a791.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/862465d1835288b2ae6d11f27507a791.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TCM- TV (RN)[/COLOR][/B]</title>
<link>https://live.tcm10.com.br/tcm10hd/stream.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/af00a626f71e3a3dfadb5a5c8ffa086c.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/af00a626f71e3a3dfadb5a5c8ffa086c.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Evangelizar (PR)[/COLOR][/B]</title>
<link>https://5f593df7851db.streamlock.net/evangelizar/tv/chunklist_w1776549185.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3492d6822618e371b1a2587c584cd988.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3492d6822618e371b1a2587c584cd988.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tela Viva Tv (RJ)[/COLOR][/B]</title>
<link>https://srv4.zcast.com.br/telavivatv/telavivatv/chunklist_w1944572432.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/ee32135a0ae4307048d3b24d0891738f.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/ee32135a0ae4307048d3b24d0891738f.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Confiego (GO)[/COLOR][/B]</title>
<link>https://stmv1.voxtvhd.com.br/tvconfiegogospel/tvconfiegogospel/chunklist_w485973756.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/dc4f4fddc2330b377037d229aee44942.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/dc4f4fddc2330b377037d229aee44942.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Carioca Internacional (RJ)[/COLOR][/B]</title>
<link>https://stmv1.duvoxtv.com.br/tvcarioca/tvcarioca/chunklist_w1254552993.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/ae3270712e80a6ee4cd2dd542fcc48c6.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/ae3270712e80a6ee4cd2dd542fcc48c6.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Jornal do Nordeste (PB)[/COLOR][/B]</title>
<link>https://video01.logicahost.com.br/tvjornaldonordeste/tvjornaldonordeste/chunklist_w309686598.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9d7d1a4b47e3583e7c715cafee8cbd02.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9d7d1a4b47e3583e7c715cafee8cbd02.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Tropical (Rede Record (RN)[/COLOR][/B]</title>
<link>https://video03.logicahost.com.br/portaldatropical/portaldatropical/chunklist_w1735768059.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/85b498edcd66663ea7dfb0c1f9fc697e.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/85b498edcd66663ea7dfb0c1f9fc697e.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Pai Eterno (GO)[/COLOR][/B]</title>
<link>https://59f1cbe63db89.streamlock.net:1443/teste01/_definst_/teste01/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/cbcbd850001e26fc5a8e03f879749644.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/cbcbd850001e26fc5a8e03f879749644.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]REDE SÉCULO 21 (SP)[/COLOR][/B]</title>
<link>https://cdn.jmvstream.com/w/LVW-10024/ngrp:LVW10024_H3QLdAY6kx_all/chunklist_b1428000.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6a5ddba30bab2ee3c622c3232dd3907b.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6a5ddba30bab2ee3c622c3232dd3907b.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Fora Tedio Tv (SP)[/COLOR][/B]</title>
<link>https://srv5.zcast.com.br/foratedio/foratedio/chunklist_w1891589032.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9ec7e3fb0435c5aadb37ced264e0d3b3.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9ec7e3fb0435c5aadb37ced264e0d3b3.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Metropole (CE)[/COLOR][/B]</title>
<link>https://cdn-fundacao-2110.ciclano.io:1443/fundacao-2110/fundacao-2110/chunklist_w343414391.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/cb11c7b420ed0d82de6c3403ee72f3d9.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/cb11c7b420ed0d82de6c3403ee72f3d9.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TVE (BA)[/COLOR][/B]</title>
<link>http://stream2.ba.gov.br/hls-live/livepkgr/_definst_/irdeb/pgm-1.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6afae9338ec57a798fb55d98b77ff0c3.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6afae9338ec57a798fb55d98b77ff0c3.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede NGT (SP)[/COLOR][/B]</title>
<link>https://isaocorp.cloudecast.com/ngt/tracks-v1/index.fmp4.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6044f74f88a8d13430fb41e4caeca5f0.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6044f74f88a8d13430fb41e4caeca5f0.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Mais Família (SP)[/COLOR][/B]</title>
<link>https://video01.logicahost.com.br/redefamiliaa/redefamiliaa/chunklist_w1869274378.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/7bb03f2570993c82583a8ce9f2e1a4c4.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/7bb03f2570993c82583a8ce9f2e1a4c4.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Rede Gospel (SP)[/COLOR][/B]</title>
<link>https://cdn.jmvstream.com/w/LVW-8719/LVW8719_AcLVAxWy5J/chunklist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/bf64a6c1f59709514cf0d763b6c0faa6.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/bf64a6c1f59709514cf0d763b6c0faa6.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Cultura Pará (PA)[/COLOR][/B]</title>
<link>https://www.portalcultura.com.br/playerhtml/funtelpa/tv_funtelpa/chunklist_w345016867.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/5c2f7367afcbeb90c88e3904aa148569.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/5c2f7367afcbeb90c88e3904aa148569.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Família (SP)[/COLOR][/B]</title>
<link>https://tv02.zas.media:1936/redefamiliaweb/redefamiliaweb/chunklist_w655465929.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9ede7e5de6ca676517ca7197759c16e7.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9ede7e5de6ca676517ca7197759c16e7.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]ULB TV[/COLOR][/B]</title>
<link>https://video01.kshost.com.br:4443/alan4876/alan4876/chunklist_w1141726047.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3dce7475bde4f62583c13a5804dad6a8.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3dce7475bde4f62583c13a5804dad6a8.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Minas (MG)[/COLOR][/B]</title>
<link>https://v4-slbps-sambavideos.akamaized.net/live/3282%2C8114%2Cec4b5a296d97fa99bf990662f5b4f8e1%3Bbase64np%3BMc8VDxqNjXKCAf8%21/amlst%3AMc_tFgfGiHOdQXPB/chunklist_.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/96ed4934fbcf5351314bfabfd78a976c.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/96ed4934fbcf5351314bfabfd78a976c.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Gospel Cartoon[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/gospelcartoon/gospelcartoon/chunklist_w219957119.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/f0a3c3c7b9a651e847d86dd71bbb5551.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/f0a3c3c7b9a651e847d86dd71bbb5551.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Geekdot[/COLOR][/B]</title>
<link>https://stream.ichibantv.com:3764/hybrid/play.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/38c67fdfc57a8a0087e02316d408473b.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/38c67fdfc57a8a0087e02316d408473b.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Nova Nordeste (Cultura (PE)[/COLOR][/B]</title>
<link>https://live.comets.com.br/tvnovanordeste/aovivo/chunklist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/da8fecf959f730dd05d649b46fa80298.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/da8fecf959f730dd05d649b46fa80298.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Brasil 2 (DF)[/COLOR][/B]</title>
<link>https://tvbrasil-stream.ebc.com.br/mux_video_ts/index-1.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/31032afb0ddcda240d10e0de80793302.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/31032afb0ddcda240d10e0de80793302.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]All Sports TV (DF)[/COLOR][/B]</title>
<link>https://5cf4a2c2512a2.streamlock.net/dgrau/dgrau/chunklist_w1016126849.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/37a7f2bbd24082bb8f947686020c3e82.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/37a7f2bbd24082bb8f947686020c3e82.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Cidade Verde (SBT (PI)[/COLOR][/B]</title>
<link>https://stmv1.transmissaodigital.com/cidadeverdenovo/cidadeverdenovo/chunklist_w1944299122.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/8ce8f1a9e2406d2acde94e2ac5d0f671.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/8ce8f1a9e2406d2acde94e2ac5d0f671.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Gospel Movie TV (SP)[/COLOR][/B]</title>
<link>https://stmv1.srvif.com/gospelf/gospelf/chunklist_w1106161706.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9ec2c361a5ce07ba0f7987bcd36dbb1d.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9ec2c361a5ce07ba0f7987bcd36dbb1d.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]RBS Mix Web Tv (PR)[/COLOR][/B]</title>
<link>https://video01.kshost.com.br:4443/ezequiel3930/ezequiel3930/chunklist_w868339855.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/84463693ae7ed42ff27b10a658f53089.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/84463693ae7ed42ff27b10a658f53089.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Kpop TV Play (SP)[/COLOR][/B]</title>
<link>https://srv1.zcast.com.br/kpoptv/kpoptv/chunklist_w2083417652.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/685286c919ab8768f8a6f70eb5dc8171.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/685286c919ab8768f8a6f70eb5dc8171.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Central Tv Brasil (PR)[/COLOR][/B]</title>
<link>https://tv02.zas.media:1936/centraltv/centraltv/chunklist_w921333567.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/84998832d7465ef731fc0e141e6c5efa.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/84998832d7465ef731fc0e141e6c5efa.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]SBT (RS)[/COLOR][/B]</title>
<link>https://cdn.jmvstream.com/w/LVW-10801/LVW10801_Xvg4R0u57n/chunklist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3c97376c5011223b08762664c3c865bb.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3c97376c5011223b08762664c3c865bb.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Santa Cecilia (SP)[/COLOR][/B]</title>
<link>https://60d88f8ce1206.streamlock.net/2063/2063/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/689f8e1fbf539be1c6e2a36b9283b324.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/689f8e1fbf539be1c6e2a36b9283b324.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TVE (RS)[/COLOR][/B]</title>
<link>https://streaming.procergs.com.br:8443/tve/stve/chunklist_w1722310835.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/fb6da5dab7f3e21853e5719473fc29f0.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/fb6da5dab7f3e21853e5719473fc29f0.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Feira de Santana (BA)[/COLOR][/B]</title>
<link>https://56b50ada2d659.streamlock.net/RadioBirikinaTV/livestream/chunklist_w174675839.m3u8?fluxustv.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/aab1d14178a0f45aec1c21e1407d30dd.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/aab1d14178a0f45aec1c21e1407d30dd.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Paraná Turismo (PR)[/COLOR][/B]</title>
<link>http://200.189.113.201/hls/tve.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6788ade239f63ac5f8262c188729285c.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/6788ade239f63ac5f8262c188729285c.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Rede Sul de Televisão (RS)[/COLOR][/B]</title>
<link>https://video05.logicahost.com.br/tvurbana/tvurbana/chunklist_w500869728.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/4236bf2d9650a0d98fcd60382765af8c.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/4236bf2d9650a0d98fcd60382765af8c.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Padre Cicero(CE)[/COLOR][/B]</title>
<link>https://video01.logicahost.com.br/tvpadrecicero/tvpadrecicero/chunklist_w1440476607.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/dab5e88e8a6365ed0890db70b53b2764.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/dab5e88e8a6365ed0890db70b53b2764.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Amazon Sat (AM)[/COLOR][/B]</title>
<link>https://amazonsat.brasilstream.com.br/hls/amazonsat/index.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/eab8e4fcefd5980ba7e4aaf007da267d.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/eab8e4fcefd5980ba7e4aaf007da267d.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Pampa + RedeTV! (RS)[/COLOR][/B]</title>
<link>https://59f1cbe63db89.streamlock.net:1443/tvpampa/_definst_/tvpampa/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/65d9059a562708573579342225f53e0b.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/65d9059a562708573579342225f53e0b.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Difusora Sul(MA)[/COLOR][/B]</title>
<link>https://stream.amsolution.net.br:8443/live/60ce4ae4b9d4c/index.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/493d51d6cb932b2b019c602bbb9db613.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/493d51d6cb932b2b019c602bbb9db613.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Novo Tempo(SP)[/COLOR][/B]</title>
<link>https://stream.live.novotempo.com/tv/smil:tvnovotempo.smil/chunklist_b1628000_slpor.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/8aee277c6f0b673837d4a25a9109a177.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/8aee277c6f0b673837d4a25a9109a177.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Diário Macapá(AP)[/COLOR][/B]</title>
<link>https://5ad482a77183d.streamlock.net/marliomelohotmail.com/marliomelohotmail.com/chunklist_w813076511.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9e62125afe944d348ab0b0721e5ed69f.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/9e62125afe944d348ab0b0721e5ed69f.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]MyTime Movie Network - Brasil[/COLOR][/B]</title>
<link>https://appletree-mytime-samsungbrazil.amagi.tv/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/f6652061e12b0246ef228236f06fa5f1.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/f6652061e12b0246ef228236f06fa5f1.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Diário Do Vale (PB)[/COLOR][/B]</title>
<link>https://5ffab78b24f94.streamlock.net/pdsertaotv/pdsertaotv/chunklist_w1673374982.m3u8</link>
<thumbnail>https://archive.org/download/channels4_profile_202305/channels4_profile.jpg</thumbnail>
<fanart>https://archive.org/download/channels4_profile_202305/channels4_profile.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TV Gideões (SC)[/COLOR][/B]</title>
<link>https://streaming01.zas.media/gideoes/programacao/playlist.m3u8</link>
<thumbnail>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3f6171c551bfebb0226b4f7d526a8e6f.webp</thumbnail>
<fanart>https://www.cxtv.com.br/img/Tvs/Logo/webp-m/3f6171c551bfebb0226b4f7d526a8e6f.webp</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

###################### canais Portugal ######################

###################### canais Espanha ######################

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]7 TV Murcia[/COLOR][/B]</title>
<link>https://rtv-murcia-live.globalmest.com/principal/smil:principal.smil/chunklist_w1858657114_b565000.m3u8</link>
<thumbnail>https://archive.org/download/7_20230505_20230505_1818/7.jpg</thumbnail>
<fanart>https://archive.org/download/7_20230505_20230505_1818/7.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]13 TV[/COLOR][/B]</title>
<link>https://live-edge-bhs-1.cdn.enetres.net/091DB7AFBD77442B9BA2F141DCC182F5021/liveld/index.m3u8</link>
<thumbnail>https://archive.org/download/13-TV/13%20TV.jpg</thumbnail>
<fanart>https://archive.org/download/13-TV/13%20TV.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Altar de Adoracion 7-24[/COLOR][/B]</title>
<link>https://vidartv2.todostreaming.es/live/radiovida-altar724.m3u8</link>
<thumbnail>https://archive.org/download/altar_202305/Altar.jpg</thumbnail>
<fanart>https://archive.org/download/altar_202305/Altar.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canal 45[/COLOR][/B]</title>
<link>https://nlb1-live.emitstream.com/hls/625csn5et2iszm9oze65/fragments/live-1500/index.m3u8</link>
<thumbnail>https://archive.org/download/Canal-45/Canal%2045.jpg</thumbnail>
<fanart>https://archive.org/download/Canal-45/Canal%2045.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canal 324[/COLOR][/B]</title>
<link>https://directes-tv-int.ccma.cat/live-origin/canal324-hls/master.m3u8</link>
<thumbnail>https://archive.org/download/Canal-324/Canal%20324.jpg</thumbnail>
<fanart>https://archive.org/download/Canal-324/Canal%20324.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canal Diocesano[/COLOR][/B]</title>
<link>https://nlb1-live.emitstream.com/hls/5i3pxfuz4az356yu22ij/fragments/live-1000/index.m3u8</link>
<thumbnail>https://archive.org/download/canal-diocesano_202305/Canal%20Diocesano.jpg</thumbnail>
<fanart>https://archive.org/download/canal-diocesano_202305/Canal%20Diocesano.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canal Extremadura[/COLOR][/B]</title>
<link>https://cdnlivevlc.codev8.net/canalextremaduralive/smil:channel1DVR.smil/playlist.m3u8</link>
<thumbnail>https://archive.org/download/Canal-Extremadura/Canal%20Extremadura.jpg</thumbnail>
<fanart>https://archive.org/download/Canal-Extremadura/Canal%20Extremadura.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canal Sur[/COLOR][/B]</title>
<link>https://cdnlive.codev8.net/rtvalive/smil:channel1.smil/chunklist_b2200000.m3u8</link>
<thumbnail>https://archive.org/download/Canal-Sur/Canal%20Sur.jpg</thumbnail>
<fanart>https://archive.org/download/Canal-Sur/Canal%20Sur.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Canela Hits[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230505chagj43g8bq0s0lq0mh0/854x480_1355200_2_f.m3u8?i=475_1058</link>
<thumbnail>https://archive.org/download/Canela-hits_202305/Canela%20Hits.jpg</thumbnail>
<fanart>https://archive.org/download/Canela-hits_202305/Canela%20Hits.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Cine Romántico[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha2h45io1t22vs77kug/854x480_550000_3_f.m3u8?i=475_656</link>
<thumbnail>https://archive.org/download/cine-r/Cine%20R.jpg</thumbnail>
<fanart>https://archive.org/download/cine-r/Cine%20R.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Distrito TV[/COLOR][/B]</title>
<link>https://nlb1-live.emitstream.com/hls/3mn7wpcv7hbmxmdzaxap/fragments/live-2000/index.m3u8</link>
<thumbnail>https://archive.org/download/distrito-tv_202305/Distrito%20TV.jpg</thumbnail>
<fanart>https://archive.org/download/distrito-tv_202305/Distrito%20TV.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]dotb Durangaldeko Telebista[/COLOR][/B]</title>
<link>https://nlb1-live.emitstream.com/hls/5f9asjsehd7gmyxsdpzu/fragments/live-2000/index.m3u8</link>
<thumbnail>https://archive.org/download/dotb-durangaldeko-telebista/dotb%20Durangaldeko%20Telebista.jpg</thumbnail>
<fanart>https://archive.org/download/dotb-durangaldeko-telebista/dotb%20Durangaldeko%20Telebista.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]ETB Basque[/COLOR][/B]</title>
<link>https://multimedia.eitb.eus/live-content/eitbbasque-hls/bitrate_3.m3u8</link>
<thumbnail>https://archive.org/download/ETB-Basco/ETB%20Basque.jpg</thumbnail>
<fanart>https://archive.org/download/ETB-Basco/ETB%20Basque.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Euronews En Español[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha2cnbg8bq0s0lm16vg/1280x720_1500000_0_f.m3u8?i=950_2577</link>
<thumbnail>https://archive.org/download/euronews-pt/Euronews%20En.jpg</thumbnail>
<fanart>https://archive.org/download/euronews-pt/Euronews%20En.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Hispan TV[/COLOR][/B]</title>
<link>https://live1.presstv.ir/live/hispan_360p/index.m3u8</link>
<thumbnail>https://archive.org/download/Hispan-TV/Hispan%20TV.jpg</thumbnail>
<fanart>https://archive.org/download/Hispan-TV/Hispan%20TV.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]BonDia TV[/COLOR][/B]</title>
<link>https://directes-tv-int.ccma.cat/live-origin/bondia-hls/bitrate_1.m3u8</link>
<thumbnail>https://archive.org/download/bon-dia-tv/BonDia%20TV.jpg</thumbnail>
<fanart>https://archive.org/download/bon-dia-tv/BonDia%20TV.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Ibiza Global Tv[/COLOR][/B]</title>
<link>https://nodo06-cloud01.streaming-pro.com/ibgrtv/hls/ibgrlive_2.m3u8</link>
<thumbnail>https://archive.org/download/ibiza-global-tv_202305/Ibiza%20Global%20Tv.jpg</thumbnail>
<fanart>https://archive.org/download/ibiza-global-tv_202305/Ibiza%20Global%20Tv.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Lancelot Televisión[/COLOR][/B]</title>
<link>https://5c0956165db0b.streamlock.net:8090/directo/_definst_/lancelot.television/playlist.m3u8</link>
<thumbnail>https://archive.org/download/lancelot-tn/Lancelot%20Tn.jpg</thumbnail>
<fanart>https://archive.org/download/lancelot-tn/Lancelot%20Tn.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Logos Tv[/COLOR][/B]</title>
<link>https://streamer1.streamhost.org/salive/logosH/chunklist_w168103485.m3u8</link>
<thumbnail>https://archive.org/download/logos-tv_202305/Logos%20Tv.jpg</thumbnail>
<fanart>https://archive.org/download/logos-tv_202305/Logos%20Tv.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Onda Cádiz[/COLOR][/B]</title>
<link>https://adc-hls.flumotion.com/adc/live_480p/chunks.m3u8</link>
<thumbnail>https://archive.org/download/onda-c/Onda%20C.jpg</thumbnail>
<fanart>https://archive.org/download/onda-c/Onda%20C.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Play Ibiza[/COLOR][/B]</title>
<link>https://d410380561e9471dab5b085811cbb01c.mediatailor.us-east-1.amazonaws.com/v1/manifest/9d062541f2ff39b5c0f48b743c6411d25f62fc25/npplayout-MUX-Ayozat/0bd5fbcb-4530-45a6-b703-2dde1b3a09c9/2.m3u8</link>
<thumbnail>https://archive.org/download/play-ibiza/Play%20Ibiza.jpg</thumbnail>
<fanart>https://archive.org/download/play-ibiza/Play%20Ibiza.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Real Madrid TV[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha06urg8bq0s0ll36ng/1920x1080_5701132_5_f.m3u8?i=475_1545</link>
<thumbnail>https://archive.org/download/real-madrid-tv/Real%20Madrid%20TV.jpg</thumbnail>
<fanart>https://archive.org/download/real-madrid-tv/Real%20Madrid%20TV.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Ritmos Inolvidables[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha33abg8bq0s0lmamc0/854x480_550000_3_f.m3u8?i=475_1081</link>
<thumbnail>https://archive.org/download/ritmos-inolvidables/Ritmos%20Inolvidables.jpg</thumbnail>
<fanart>https://archive.org/download/ritmos-inolvidables/Ritmos%20Inolvidables.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]RTV Vida[/COLOR][/B]</title>
<link>https://vidartv2.todostreaming.es/live/radiovida-emisiontvhd.m3u8</link>
<thumbnail>https://archive.org/download/rtv-vida_202305/RTV%20Vida.jpg</thumbnail>
<fanart>https://archive.org/download/rtv-vida_202305/RTV%20Vida.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Español - Cine Y Series[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha1s3bjdm8fonriv7ng/854x480_1355200_2_f.m3u8?i=475_2152</link>
<thumbnail>https://archive.org/download/r_20230505/R.jpg</thumbnail>
<fanart>https://archive.org/download/r_20230505/R.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Runtime Español[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha23p9pnj1vb8te7u30/854x480_1355200_2_f.m3u8?i=475_2649</link>
<thumbnail>https://archive.org/download/runtime_202305/Runtime.jpg</thumbnail>
<fanart>https://archive.org/download/runtime_202305/Runtime.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]San Roque Tv[/COLOR][/B]</title>
<link>https://cdnlivevlc.codev8.net/aytosanroquelive/smil:channel1.smil/chunklist_b1500000.m3u8</link>
<thumbnail>https://archive.org/download/SA-ROQUE-TV/SRoque%20Tv.jpg</thumbnail>
<fanart>https://archive.org/download/SA-ROQUE-TV/SRoque%20Tv.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Solidaria TV[/COLOR][/B]</title>
<link>https://canadaremar2.todostreaming.es/live/solidariatv-webhd.m3u8</link>
<thumbnail>https://archive.org/download/stv_20230505/STV.jpg</thumbnail>
<fanart>https://archive.org/download/stv_20230505/STV.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TBN España[/COLOR][/B]</title>
<link>https://edge.xn--tbnespaa-j3a.es/LiveApp/streams/tbnlive.m3u8</link>
<thumbnail>https://ia902608.us.archive.org/17/items/tbn_20230505/TBN.jpg</thumbnail>
<fanart>https://ia902608.us.archive.org/17/items/tbn_20230505/TBN.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Teleganés[/COLOR][/B]</title>
<link>https://nlb2-live.emitstream.com/hls/5z6oj7ziwxzfnj78vg2m/fragments/live-2000/index.m3u8</link>
<thumbnail>https://archive.org/download/Telega/Telega.jpg</thumbnail>
<fanart>https://archive.org/download/Telega/Telega.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Telemadrid[/COLOR][/B]</title>
<link>https://telemadridhls2-live-hls.secure2.footprint.net/egress/chandler/telemadrid/telemadrid_1/bitrate_1.m3u8</link>
<thumbnail>https://archive.org/download/telemadrid_202305/Telemadrid.jpg</thumbnail>
<fanart>https://archive.org/download/telemadrid_202305/Telemadrid.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Teve 4[/COLOR][/B]</title>
<link>https://nlb1-live.emitstream.com/hls/646wzsnqyforndavy6de/fragments/teve4/index.m3u8</link>
<thumbnail>https://archive.org/download/TEVE-4/Teve%204.jpg</thumbnail>
<fanart>https://archive.org/download/TEVE-4/Teve%204.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Toon Goggles en Español[/COLOR][/B]</title>
<link>https://stream.ads.ottera.tv/cl/230504cha3ts9opv5pil5u2350/1280x720_3071200_0_f.m3u8?i=475_771</link>
<thumbnail>https://archive.org/download/toon-g/Toon%20G.jpg</thumbnail>
<fanart>https://archive.org/download/toon-g/Toon%20G.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Barbastro[/COLOR][/B]</title>
<link>https://common01.todostreaming.es/live/tvbarbastro-livestream.m3u8</link>
<thumbnail>https://archive.org/download/TV-barbastro_202305/Tv%20Barbastro.jpg</thumbnail>
<fanart>https://archive.org/download/TV-barbastro_202305/Tv%20Barbastro.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]Tv Melilla[/COLOR][/B]</title>
<link>https://tvmelilla-hls-rm-lw.flumotion.com/tvmelilla/live-fake-ori_med/chunks.m3u8</link>
<thumbnail>https://archive.org/download/TV-melilla_202305/Tv%20Melilla.jpg</thumbnail>
<fanart>https://archive.org/download/TV-melilla_202305/Tv%20Melilla.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TVE-24h[/COLOR][/B]</title>
<link>https://rtvelivestream-clnx.rtve.es/rtvesec/24h/24h_main.m3u8</link>
<thumbnail>https://archive.org/download/TV-24h/TVE%20-%2024h.jpg</thumbnail>
<fanart>https://archive.org/download/TV-24h/TVE%20-%2024h.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>

<item>
<title>[B][COLOR lime]●[/COLOR] [COLOR gold]TVG-Galicia TV América[/COLOR][/B]</title>
<link>https://america-crtvg.flumotion.com/crtvg/america_med/chunks.m3u8</link>
<thumbnail>https://archive.org/download/tvg_20230505/TVG.jpg</thumbnail>
<fanart>https://archive.org/download/tvg_20230505/TVG.jpg</fanart>
<info>[COLOR yellow]Se o canal da live TV estiver fora do ar, isso pode significar que há um problema de conexão com a internet ou que o servidor que hospeda o link está com problemas técnicos.[/COLOR]</info>
</item>
































































